language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip3 install pipenv
  - pipenv install --dev
  - cp tests/mocks.example.py tests/mocks.py
script:
  - pipenv run pytest
  - pipenv run make html
after_success:
  - pipenv run cover
  - pipenv run coveralls
