language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip3 install pipenv
  - pipenv install --dev
  - cp config.example.py config.py
script:
  - pipenv run pytest
after_success:
  - pipenv run cover
  - pipenv run coveralls
